// client-side-rendering/vue-instantsearch/src/App.vue
<template>
  <div>
    <header class="header">
      <h1 class="header-title">
        <a href="/">Client-Side Rendering</a>
      </h1>
      <p class="header-subtitle">
        using
        <a href="https://www.algolia.com/doc/api-reference/widgets/vue/">
          Vue InstantSearch
        </a>
      </p>
    </header>

    <div class="container">
      <ais-instant-search
        :search-client="searchClient"
        index-name="instant_search"
        :routing="routing"
      >
        <div class="search-panel">
          <div class="search-panel__results">
            <div class="menu">
              <ais-menu attribute="categories" />
            </div>
            <div class="searchbox">
              <ais-search-box placeholder />
            </div>
            <ais-hits>
              <template slot="item" slot-scope="{ item }">
                <article>
                  <h1>
                    <ais-highlight :hit="item" attribute="name" />
                  </h1>
                  <p>
                    <ais-highlight :hit="item" attribute="description" />
                  </p>
                  <p>
                    <ais-highlight :hit="item" attribute="brand" />
                  </p>
                </article>
              </template>
            </ais-hits>

            <div class="pagination">
              <ais-pagination
                :show-first="false"
                :show-last="false"
                :total-pages="5"
              />
            </div>
          </div>
        </div>
      </ais-instant-search>
    </div>
  </div>
</template>

<script>
import algoliasearch from 'algoliasearch/lite';
import { history } from 'instantsearch.js/es/lib/routers';
import { simple } from 'instantsearch.js/es/lib/stateMappings';

export default {
  data() {
    return {
      searchClient: algoliasearch(
        'latency',
        '6be0576ff61c053d5f9a3225e2a90f76'
      ),
      routing: {
        router: history(),
        stateMapping: simple(),
      },
    };
  },
};
</script>

<style>
body,
h1 {
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
}

em {
  background: cyan;
  font-style: normal;
}

.header {
  display: flex;
  align-items: center;
  min-height: 50px;
  padding: 0.5rem 1rem;
  background-image: linear-gradient(to right, #4dba87, #2f9088);
  color: #fff;
  margin-bottom: 1rem;
}

.header a {
  color: #fff;
  text-decoration: none;
}

.header-title {
  font-size: 1.2rem;
  font-weight: normal;
}

.header-title::after {
  content: ' ▸ ';
  padding: 0 0.5rem;
}

.header-subtitle {
  font-size: 1.2rem;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 1rem;
}

.search-panel {
  display: flex;
}

.search-panel__results {
  flex: 3;
}

.searchbox {
  margin-bottom: 2rem;
}

.pagination {
  margin: 2rem auto;
  text-align: center;
}
</style>

// client-side-rendering/angular-instantsearch/src/app/app.component.ts
import { Component } from '@angular/core';
import * as algoliasearch from 'algoliasearch';

const searchClient = algoliasearch(
  'latency',
  '6be0576ff61c053d5f9a3225e2a90f76'
);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  public config = {
    indexName: 'instant_search',
    searchClient,
    routing: true,
  };
}

<header class="header">
  <h1 class="header-title">
    <a href="/">Client-Side Rendering</a>
  </h1>
  <p class="header-subtitle">
    using
    <a href="https://www.algolia.com/doc/api-reference/widgets/angular/">
      Angular InstantSearch
    </a>
  </p>
</header>

<div class="container">
  <ais-instantsearch [config]="config">
    <div class="search-panel">
      <div class="search-panel__results">
        <div class="menu">
          <ais-menu attribute="categories"></ais-menu>
        </div>
        <div class="searchbox">
          <ais-search-box
            placeholder="Search for a product, brand, color, …"
          ></ais-search-box>
        </div>
        <ais-hits>
          <ng-template let-hits="hits" let-results="results">
            <div *ngIf="hits.length === 0">
              No results found matching <strong></strong>.
            </div>

            <ol class="ais-Hits-list">
              <li class="ais-Hits-item" *ngFor="let hit of hits">
                <article>
                  <h1>
                    <ais-highlight attribute="name" [hit]="hit"></ais-highlight>
                  </h1>
                  <p>
                    <ais-highlight
                      attribute="description"
                      [hit]="hit"
                    ></ais-highlight>
                  </p>
                  <p>
                    <ais-highlight
                      attribute="brand"
                      [hit]="hit"
                    ></ais-highlight>
                  </p>
                </article>
              </li>
            </ol>
          </ng-template>
        </ais-hits>

        <div class="pagination">
          <ais-pagination
            showFirst="false"
            showLast="false"
            totalPages="4"
          ></ais-pagination>
        </div>
      </div>
    </div>
  </ais-instantsearch>
</div>
